// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwifhQg5aucm6H1eU-YTgDtJJ9QBDS8Yg',
    appId: '1:922869867568:web:9bfc4564a2a13285ebf9f5',
    messagingSenderId: '922869867568',
    projectId: 'movies-app-7310e',
    authDomain: 'movies-app-7310e.firebaseapp.com',
    storageBucket: 'movies-app-7310e.appspot.com',
    measurementId: 'G-KPM1QBTXCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcejTidux1MyUAQl5eWS_dX1hwp8AZe74',
    appId: '1:922869867568:android:dfec499733737c65ebf9f5',
    messagingSenderId: '922869867568',
    projectId: 'movies-app-7310e',
    storageBucket: 'movies-app-7310e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzc4HIxDc2lnM-GHqGvq675Yv-gcNwhoc',
    appId: '1:922869867568:ios:ad60e89510aae816ebf9f5',
    messagingSenderId: '922869867568',
    projectId: 'movies-app-7310e',
    storageBucket: 'movies-app-7310e.appspot.com',
    iosClientId: '922869867568-s2qd8piq9gp3rd9ja341o598cvsapsr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzc4HIxDc2lnM-GHqGvq675Yv-gcNwhoc',
    appId: '1:922869867568:ios:9f3300f043c84e0debf9f5',
    messagingSenderId: '922869867568',
    projectId: 'movies-app-7310e',
    storageBucket: 'movies-app-7310e.appspot.com',
    iosClientId: '922869867568-181cuvhimi44adio7ie1anp5u3u8ndfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
